security:
  encoders:
    App\Entity\User:
        algorithm: argon2i




  providers:
    user_db:
      entity:
          class: App\Entity\User
          property: email
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
        entity:
            class: App\Entity\User
            property: email
    # used to reload user from session & other features (e.g. switch_user)
    # used to reload user from session & other features (e.g. switch_user)
    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      provider: user_db
      form_login:
        login_path: login
        check_path: login
      guard:
          authenticators:
              - App\Security\LoginFormAuthenticator

  access_control:
   - { path: ^/admin, roles: ROLE_ADMIN }
   - { path: ^/profile, roles: ROLE_USER }